-- Explore all objects in the database 

Select * from INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database

select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers'

-- Explore all countries our customers come from.
select DISTINCT country FROM dim_customers

-- Explore all categories 'The Major Divisions'
SELECT DISTINCT category, subcategory, product_name FROM dim_products
order by 1,2,3

-- find the date of the first and lasr order 
select 
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS order_range_years
from fact_sales;

--Find the youngest and the oldest customer 

SELECT 
MIN(birthdate) as oldest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) as youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_customer
from dim_customers;



-- Find total sales
SELECT SUM(sales_amount) AS total_sales FROM fact_sales

-- Find how many times are sold
SELECT SUM(quantity) AS total_quantity FROM fact_sales

-- Find the average selling price 
SELECT AVG(price) AS average_price FROM fact_sales


-- Find total number of orders 
SELECT COUNT(order_number) AS total_orders FROM fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM fact_sales

-- Find the total number of products 
SELECT COUNT(product_key) AS total_products FROM dim_products
SELECT COUNT(DISTINCT product_key) AS total_products FROM dim_products

--Find the total number of customers 
SELECT COUNT(customer_key) as total_customers FROM dim_customers


-- Find the total of customers that has placed an order 
SELECT COUNT(DISTINCT customer_key) as total_orders FROM fact_sales


-- Generate a report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_Value FROM fact_sales
UNION ALL 
SELECT 'Total Quantity' as measure_name, SUM(quantity) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Average Price' as measure_name, AVG(price) AS measure_value FROM fact_sales
UNION ALL 
SELECT 'Total Orders' as measure_name, COUNT(DISTINCT order_number) AS measure_value FROM fact_sales
UNION ALL 
SELECT 'Total Products' as measure_name, COUNT(DISTINCT product_key) AS measure_value FROM dim_products
UNION ALL 
SELECT 'Total Customers' as measure_name, COUNT(customer_key) as measure_value  FROM dim_customers


-- Find total customers by country
SELECT 
country,
COUNT(customer_key) as total_customers
from dim_customers
group by country 

-- find total customers by gender
SELECT 
gender,
COUNT(customer_key) as total_customers_by_gender
from dim_customers
group by gender 

-- find total product by category 
SELECT 
category,
COUNT(product_key) as total_products
from dim_products
group by category

-- What is the average cost in each category
SELECT 
category,
AVG (cost) as average_cost
from dim_products
group by category
order by average_cost DESC 



-- What is the total revenue generated for each category

SELECT 
p.category,
SUM(f.sales_amount) as total_revenue
from fact_sales f
LEFT JOIN dim_products p
ON P.product_key = f.product_key
group by category
order by total_revenue DESC 

-- What is the total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue 
from fact_sales f
left join dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc 


-- what is the distribution of sold items across countires
select
c.country,
sum(f.quantity) as total_sold_items 
from fact_sales f
left join dim_customers c
on c.customer_key = f.customer_key
group by 
c.country
order by total_sold_items desc

-- which 5 products generate the highest revenue

SELECT top 5
p.product_name,
sum(f.sales_amount) as total_revenue 
from fact_sales f
left join dim_products p
on p.product_key = f.product_key
group by 
p.product_name
order by total_revenue desc 


SELECT *
from(
	select
	p.product_name,
	sum(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY sum(f.sales_amount) DESC) AS rank_products
	from fact_sales f
	left join dim_products p
	on p.product_key = f.product_key
	group by 
	p.product_name)t
WHERE rank_products <= 5

-- the 3 customers with the fewest order placed 

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) as total_orders 
from fact_sales f
left join dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_orders 




-- What are the worst-performing products in term of sales


SELECT top 5
p.product_name,
sum(f.sales_amount) as total_revenue 
from fact_sales f
left join dim_products p
on p.product_key = f.product_key
group by 
p.product_name
order by total_revenue  


